#!/usr/bin/python3

"""
Lê, na entrada padrão, um programa na linguagem de montagem da máquina
virtual e retorna um programa em C que executa este programa.

Uso:
    ./montador < entrada
"""
from sys import stdin
import sys

f = open("motor.c", "w")
sys.stdout = f

lines = stdin.readlines()

ip = 0
tabsim = {}


for l in lines:
    try:
        l = l[:l.index('#')]
    except:
        pass
    if l.isspace():
        continue
    keys = l.split()
    if len(keys) > 0 and keys[0].endswith(":"):
        label = keys[0][:-1]              #jogando fora o ':'
        tabsim[label]=ip
    ip += 1

ip = 0

print("#include <stdio.h>\n#include \"maq.h\" \n")

print("INSTR prog[] = {")
for l in lines:
    label = op = ""
    arg   = 0
    try:
        l = l[:l.index('#')]
    except:
        pass
    if len(l) == 1 or len(l) == 0:
        print("")
        continue
    keys = l.split()
    if len(keys) > 0 and keys[0].endswith(":"):
        keys.pop(0)
    if len(keys) > 0:
        op = keys.pop(0)
    if len(keys) > 0:
        arg = keys.pop(0)
        if arg in tabsim:
            arg = tabsim[arg]
    if op != "":
        print("  {%s, %s},"%(op,arg))
    else:
        print()
    ip += 1
print("};\n")

print("int main(int ac, char **av) {")
print("\tMaquina *maq = cria_maquina(prog);")
print("\tputs(\"---\");")
print("\texec_maquina(maq, 100000);")
print("\tputs(\"---\");")
print("\tdestroi_maquina(maq);")
print("\treturn 0;")
print("}")


# Local variables:
# mode: python
# End:
